# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpt_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(405, 100)
        Form.setStyleSheet("background-color:rgb(0,0,0)")
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gpt_chat = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gpt_chat.sizePolicy().hasHeightForWidth())
        self.gpt_chat.setSizePolicy(sizePolicy)
        self.gpt_chat.setMinimumSize(QtCore.QSize(320, 50))
        self.gpt_chat.setMaximumSize(QtCore.QSize(320, 16777215))
        self.gpt_chat.setStyleSheet("background-color:  rgb(45, 45, 45);\n"
"border-radius:20px;\n"
"font: 12pt \"Segoe UI\";\n"
"color: rgb(255,255,255);")
        self.gpt_chat.setTextFormat(QtCore.Qt.PlainText)
        self.gpt_chat.setWordWrap(True)
        self.gpt_chat.setOpenExternalLinks(False)
        self.gpt_chat.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.gpt_chat.setObjectName("gpt_chat")
        self.horizontalLayout.addWidget(self.gpt_chat)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gpt_icon = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gpt_icon.sizePolicy().hasHeightForWidth())
        self.gpt_icon.setSizePolicy(sizePolicy)
        self.gpt_icon.setMinimumSize(QtCore.QSize(50, 50))
        self.gpt_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.gpt_icon.setText("")
        self.gpt_icon.setPixmap(QtGui.QPixmap(":/AI/300ppi/gpt.png"))
        self.gpt_icon.setScaledContents(True)
        self.gpt_icon.setObjectName("gpt_icon")
        self.verticalLayout_2.addWidget(self.gpt_icon)
        spacerItem1 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.gpt_chat.setText(_translate("Form", "To complete your request and create great images in Midjourney, I will need to define the subject\'s characteristics, pose, background, lighting, and style. I will create 5 optimized Midjourney commands to you and repeat this process until your request is completed."))
import gui.resources.resources_rc
