# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 400))
        self.frame.setStyleSheet("*{\n"
"    background:rgb(0,0,0);\n"
"    font: 15pt \"Yu Gothic UI\";\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.time_label = QtWidgets.QLabel(self.frame)
        self.time_label.setGeometry(QtCore.QRect(20, 120, 360, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("*{\n"
"    font-size: 100px\n"
"}")
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setWordWrap(False)
        self.time_label.setObjectName("time_label")
        self.StartChat = QtWidgets.QPushButton(self.frame)
        self.StartChat.setGeometry(QtCore.QRect(20, 330, 360, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.StartChat.setFont(font)
        self.StartChat.setStyleSheet("/* 默认状态 */\n"
"QPushButton {\n"
"    background-color: rgb(45,45,45);\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 25px;/* 设置圆角半径 */\n"
"}\n"
"\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background-color: rgb(70, 227, 162);\n"
"    border-radius: 25px; /* 设置圆角半径 */\n"
"}\n"
"\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 255, 181);\n"
"    border-radius: 25px; /* 设置圆角半径 */\n"
"}\n"
"")
        self.StartChat.setObjectName("StartChat")
        self.day_label = QtWidgets.QLabel(self.frame)
        self.day_label.setGeometry(QtCore.QRect(230, 50, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.day_label.setFont(font)
        self.day_label.setStyleSheet("*{\n"
"    font-size: 30px\n"
"}")
        self.day_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.day_label.setObjectName("day_label")
        self.date_label = QtWidgets.QLabel(self.frame)
        self.date_label.setGeometry(QtCore.QRect(230, 10, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.date_label.setFont(font)
        self.date_label.setStyleSheet("*{\n"
"    font-size: 30px\n"
"}")
        self.date_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.date_label.setObjectName("date_label")
        self.CircularProgress = QtWidgets.QWidget(self.frame)
        self.CircularProgress.setGeometry(QtCore.QRect(20, 20, 120, 80))
        self.CircularProgress.setStyleSheet("*{\n"
"    background-color:rgb(45,45,45);\n"
"}")
        self.CircularProgress.setObjectName("CircularProgress")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time_label.setText(_translate("MainWindow", "20:30"))
        self.StartChat.setText(_translate("MainWindow", "Start Chat"))
        self.day_label.setText(_translate("MainWindow", "Tuesday"))
        self.date_label.setText(_translate("MainWindow", "15 May"))
